### ISSUE TITLE
A batch request cannot contain more than 1000 single requests

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/googleapps-managementagent#10]
Trying to export with a large change in external members..

Getting the error

>    at Google.Apis.Requests.BatchRequest.Queue[TResponse](IClientServiceRequest request, OnResponse`1 callback) in C:\Users\cloudsharp\Documents\GitHub\google-api-dotnet-client\Src\Support\GoogleApis\Apis\Requests\BatchRequest.cs:line 147
>    at Lithnet.GoogleApps.GroupMemberRequestFactory.RemoveMembers(String id, IList`1 members, Boolean throwOnMissingMember)
>    at Lithnet.GoogleApps.MA.ApiInterfaceGroupMembership.ApplyChanges(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroupMembership.cs:line 33
>    at Lithnet.GoogleApps.MA.ApiInterfaceGroup.ApplyChanges(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroup.cs:line 120
>    at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeUpdate(CSEntryChange csentry, CSEntryChange deltaCSEntry, MASchemaType maType, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 144
>    at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeObject(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 65
>    at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChange(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 16
>    at Lithnet.GoogleApps.MA.ManagementAgent.<>c__DisplayClass33_0.<PutExportEntries>b__0(CSEntryChange csentry) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 136

****************************************
An exception has occurred in <PutExportEntries>b__0
Type: System.InvalidOperationException

Message: A batch request cannot contain more than 1000 single requests
Source: Google.Apis
TargetSite: Void Queue[TResponse](Google.Apis.Requests.IClientServiceRequest, OnResponse`1)
StackTrace:
   at Google.Apis.Requests.BatchRequest.Queue[TResponse](IClientServiceRequest request, OnResponse`1 callback) in C:\Users\cloudsharp\Documents\GitHub\google-api-dotnet-client\Src\Support\GoogleApis\Apis\Requests\BatchRequest.cs:line 147
   at Lithnet.GoogleApps.GroupMemberRequestFactory.RemoveMembers(String id, IList`1 members, Boolean throwOnMissingMember)
   at Lithnet.GoogleApps.MA.ApiInterfaceGroupMembership.ApplyChanges(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroupMembership.cs:line 33
   at Lithnet.GoogleApps.MA.ApiInterfaceGroup.ApplyChanges(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroup.cs:line 120
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeUpdate(CSEntryChange csentry, CSEntryChange deltaCSEntry, MASchemaType maType, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 144
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeObject(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 65
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChange(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 16
   at Lithnet.GoogleApps.MA.ManagementAgent.<>c__DisplayClass33_0.<PutExportEntries>b__0(CSEntryChange csentry) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 136
****************************************

**Comment by ryannewington** [comment]
Can you see if this build resolves the issue?

[Lithnet.GoogleApps.MA.Setup.zip](https://github.com/lithnet/googleapps-managementagent/files/528411/Lithnet.GoogleApps.MA.Setup.zip)

**Comment by ryannewington** [comment]
Another build to try

[Lithnet.GoogleApps.MA.Setup.zip](https://github.com/lithnet/googleapps-managementagent/files/530616/Lithnet.GoogleApps.MA.Setup.zip)

**Comment by ryannewington** [comment]
Fixed in v1.1.6132
