### ISSUE TITLE
Unable to delete telephone number from shared contact

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/googleapps-managementagent#12]
*******************************************************************************
23/11/2016 6:50:41 AM: Opening export connection
-------------------------------------------------------------------------------
23/11/2016 6:50:51 AM: Starting export Update for contact:Sally.Newman@d2-monash-edu.ga-staff-dev.monash.edu
23/11/2016 6:50:51 AM: Performing FULL update operation for contact:Sally.Newman@d2-monash-edu.ga-staff-dev.monash.edu
23/11/2016 6:50:52 AM: Updating phones_work -> <null>
23/11/2016 6:50:52 AM: An unexpected error occurred while processing contact:Sally.Newman@d2-monash-edu.ga-staff-dev.monash.edu
****************************************
An exception has occurred in <PutExportEntries>b__0
Type: Google.GData.Client.GDataRequestException
Message: Execution of request failed: https://www.google.com/m8/feeds/contacts/ga-staff-dev.monash.edu/full/1c739e8d8bfe7596
Source: Google.GData.Client
TargetSite: Void Execute()
StackTrace:
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.Service.EntrySend(Uri feedUri, AtomBase baseEntry, GDataRequestType type, AsyncSendData data)
   at Google.GData.Client.Service.Update[TEntry](TEntry entry)
   at Lithnet.GoogleApps.ContactRequestFactory.Update(ContactEntry c)
   at Lithnet.GoogleApps.MA.ApiInterfaceContact.ApplyChanges(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceContact.cs:line 106
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeUpdate(CSEntryChange csentry, CSEntryChange deltaCSEntry, MASchemaType maType, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 140
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeObject(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 61
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChange(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 16
   at Lithnet.GoogleApps.MA.ManagementAgent.<>c__DisplayClass34_0.<PutExportEntries>b__0(CSEntryChange csentry) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 148
****************************************
****************************************
Inner exception details
Type: System.Net.WebException
Status: ProtocolError
Message: The remote server returned an error: (400) Bad Request.
Source: System
TargetSite: System.Net.WebResponse GetResponse()
StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
****************************************
-------------------------------------------------------------------------------
23/11/2016 6:50:52 AM: Closing export connection: Normal
23/11/2016 6:50:52 AM: Writing 0 delta entries to file
*******************************************************************************

In the log the phone_work is being written out as < null > (ignore spacing) but for a user it goes out as #null# <-- Don't know if that makes a difference. 

Saying that < null > of a shared contact department works.

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/googleapps-managementagent/releases/tag/v1.1.6181
