### ISSUE TITLE
All Object Types must be selected 

### ISSUE THREAD

**Issue by farrowtj** [lithnet/googleapps-managementagent#15]
I only had Users selected in the object type window and was not able to do a full sync.  I then selected all of the object types except for domain and still a full sync would fail.  Once I selected all of the object types, the full sync worked fine.

-Todd F.

**Comment by farrowtj** [comment]
Here is the error code and stack trace:

The extensible extension returned an unsupported error.
The stack trace is:

 "System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Collections.ObjectModel.KeyedCollection`2.get_Item(TKey key)
   at Lithnet.GoogleApps.MA.ApiInterfaceGroup.GetItems(IManagementAgentParameters config, Schema schema, BlockingCollection`1 collection) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroup.cs:line 228
   at Lithnet.GoogleApps.MA.ManagementAgent.OpenImportConnectionFull(Schema types) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 254
   at Lithnet.GoogleApps.MA.ManagementAgent.OpenImportConnection(KeyedCollection`2 configParameters, Schema types, OpenImportConnectionRunStep importRunStep) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 231
Forefront Identity Manager 4.4.1459.0"

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/googleapps-managementagent/releases/tag/v1.1.6347
