### ISSUE TITLE
Unable to retrieve schema

### ISSUE THREAD

**Issue by Expat1905** [lithnet/googleapps-managementagent#30]
Hi Ryan,

I am trying to fire up the MA and have followed - hopefully correctly - your instructions on creating the service account etc. but I am getting the error "Unable to retrieve schema".  What I am not able to tell though is whether the problem is with my service account creation, firewall from within my organization or something else.

I realize this is rather vague, but I was wondering if you would have any connectivity/authentication troubleshooting tips you could share?  For example, is there any way to validate the Google configuration is correct, or the communication with Google is working correctly?

Thanks,
Andy

**Comment by ryannewington** [comment]
Hi @Expat1905,

There should be an error logged by the sync engine in the event log. Can you send me the details of that message?

ryan

**Comment by Expat1905** [comment]
Hi Ryan,

Thanks for reaching back to me on this.  Here is the error from the event log:

The extensible extension returned an unsupported error.
The stack trace is:
 "System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Google.Apis.Requests.ClientServiceRequest`1.Execute() in C:\Apiary\v1.25\Src\Support\GoogleApis\Apis\Requests\ClientServiceRequest.cs:line 101
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithBackoff[T](ClientServiceRequest`1 request, Int32 retryAttempts)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithBackoff[T](ClientServiceRequest`1 request)
   at Lithnet.GoogleApps.SchemaRequestFactory.HasSchema(String customerID, String schemaName)
   at Lithnet.GoogleApps.MA.SchemaBuilder.GetSchema(IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\Schema\SchemaBuilder.cs:line 31
   at Lithnet.GoogleApps.MA.ManagementAgent.GetSchema(KeyedCollection`2 configParameters) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 405
Forefront Identity Manager 4.5.26.0"

Thanks,
Andy

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ryannewington** [comment]
Hi @Expat1905,

That error seems to indicate a timeout trying to connect to Google. Do you have any proxies in between you and Google that could be causing this?

Ryan

**Comment by Expat1905** [comment]
Hi Ryan,

I was wondering the same thing over the weekend so I will verify this tomorrow.

Thanks,
Andy

On Aug 5, 2018 5:03 PM, Ryan Newington <notifications@github.com> wrote:

Hi @Expat1905<https://github.com/Expat1905>,

That error seems to indicate a timeout trying to connect to Google. Do you have any proxies in between you and Google that could be causing this?

Ryan

**Comment by Expat1905** [comment]
Hi Ryan,

I resolved my connectivity (proxy) problem but now have had an authentication problem.


The extensible extension returned an unsupported error.

The stack trace is:

 "Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"unauthorized_client", Description:"Client is unauthorized to retrieve access tokens using this method.", Uri:""

   at Google.Apis.Requests.ClientServiceRequest`1.Execute() in C:\Apiary\v1.25\Src\Support\GoogleApis\Apis\Requests\ClientServiceRequest.cs:line 101

   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithBackoff[T](ClientServiceRequest`1 request, Int32 retryAttempts)

   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithBackoff[T](ClientServiceRequest`1 request)

   at Lithnet.GoogleApps.SchemaRequestFactory.HasSchema(String customerID, String schemaName)

   at Lithnet.GoogleApps.MA.SchemaBuilder.GetSchema(IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\Schema\SchemaBuilder.cs:line 31

   at Lithnet.GoogleApps.MA.ManagementAgent.GetSchema(KeyedCollection`2 configParameters) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 405

Forefront Identity Manager 4.5.26.0"


Looking at the Authentication step in the instructions you provide an API scope, but I saw you quote a different one in a thread with somebody else having auth problems. Here are the two options I have :


https://www.googleapis.com/auth/admin.directory.domain.readonly,https://apps-apis.google.com/a/feeds/emailsettings/2.0/,http://www.google.com/m8/feeds/contacts/,https://www.googleapis.com/auth/admin.directory.user,https://www.googleapis.com/auth/admin.directory.group,https://www.googleapis.com/auth/admin.directory.group.member,https://www.googleapis.com/auth/admin.directory.userschema,https://www.googleapis.com/auth/apps.groups.settings,https://www.googleapis.com/auth/admin.directory.resource.calendar,https://www.googleapis.com/auth/calendar



https://www.googleapis.com/auth/admin.directory.user,https://www.googleapis.com/auth/admin.directory.userschema.readonly,https://apps-apis.google.com/a/feeds/emailsettings/2.0/,https://www.googleapis.com/auth/admin.directory.group,https://www.googleapis.com/auth/admin.directory.group.member,https://www.googleapis.com/auth/apps.groups.settings,https://www.googleapis.com/auth/admin.directory.domain.readonly,http://www.google.com/m8/feeds/contacts/,https://www.googleapis.com/auth/calendar,https://www.googleapis.com/auth/admin.directory.resource.calendar,https://www.googleapis.com/auth/admin.directory.resource.calendar,https://www.googleapis.com/auth/admin.directory.resource.calendar,https://www.googleapis.com/auth/admin.directory.domain.readonly

Would you be so kind as to confirm the client access auth settings I should use (and if, based on the error above, I am actually even going down the right path)?

Thanks,
Andy
________________________________

**Comment by ryannewington** [comment]
Hi Andy,

The correct API scopes are the ones on the wiki page.

https://github.com/lithnet/googleapps-managementagent/wiki/Creating-and-authorizing-a-Google-Apps-service-account

Did you make sure that in the last step you put the client ID and not the service account name in the client name field? I've often found that updating this field doesn't work. You need to delete the entry and create a new one, and wait a few minutes for trying again.

If that doesn't work, I'd go through the process of creating a service account again from scratch. There may have been a step you missed along the way, and Google is very unforgiving with this setup if anything is wrong. Unfortunately, it doesn't give us a nice way to tell which part of the set up was wrong.

Let me know how you go.

Ryan

**Comment by Expat1905** [comment]
Hi Ryan,

Still not having any luck with this and we have also tried a setup outside our network to try and eliminate the proxy.

I have one more error from the logs, in case this is of any help?

The extensible extension returned an unsupported error.
The stack trace is:

 "Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_grant", Description:"Invalid email or User ID", Uri:""
   at Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.<RequestAccessTokenAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.ServiceCredential.<GetAccessTokenForRequestAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.<GetAccessTokenForRequestAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.ServiceCredential.<InterceptAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Http.ConfigurableMessageHandler.<SendAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithBackoff[T](ClientServiceRequest`1 request, Int32 retryAttempts)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithBackoff[T](ClientServiceRequest`1 request)
   at Lithnet.GoogleApps.SchemaRequestFactory.HasSchema(String customerID, String schemaName)
   at Lithnet.GoogleApps.MA.SchemaBuilderAdvancedUsers.GetSchemaType(IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\Schema\SchemaBuilderAdvancedUsers.cs:line 11
   at Lithnet.GoogleApps.MA.SchemaBuilder.GetSchema(IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\Schema\SchemaBuilder.cs:line 25
   at Lithnet.GoogleApps.MA.ManagementAgent.GetSchema(KeyedCollection`2 configParameters) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 413
Forefront Identity Manager 4.5.26.0"


Do you have any other suggestions on what I might look for?

Thanks,
Andy

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Expat1905** [comment]
Oh, BTW, I am working with Jeff Ingalls and he said he had mentioned I might reach out…just helping you connect the dots.

Thanks,
Andy


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by briuccio** [comment]
Hello Ryan,
we have the same issue, do you have any further suggestion?

The extensible extension returned an unsupported error.
 The stack trace is:
 
 "Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"unauthorized_client", Description:"Client is unauthorized to retrieve access tokens using this method.", Uri:""
   at Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.<RequestAccessTokenAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.ServiceCredential.<GetAccessTokenForRequestAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.<GetAccessTokenForRequestAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.ServiceCredential.<InterceptAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Http.ConfigurableMessageHandler.<SendAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithBackoff[T](ClientServiceRequest`1 request, Int32 retryAttempts)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithBackoff[T](ClientServiceRequest`1 request)
   at Lithnet.GoogleApps.SchemaRequestFactory.HasSchema(String customerID, String schemaName)
   at Lithnet.GoogleApps.MA.SchemaBuilderAdvancedUsers.GetSchemaType(IManagementAgentParameters config) in C:\MIM\TUTTOGoogleMIM\googleapps-managementagent-master\src\Lithnet.GoogleApps.MA\Schema\SchemaBuilderAdvancedUsers.cs:line 11
   at Lithnet.GoogleApps.MA.SchemaBuilder.GetSchema(IManagementAgentParameters config) in C:\MIM\TUTTOGoogleMIM\googleapps-managementagent-master\src\Lithnet.GoogleApps.MA\Schema\SchemaBuilder.cs:line 25
   at Lithnet.GoogleApps.MA.ManagementAgent.GetSchema(KeyedCollection`2 configParameters) in C:\MIM\TUTTOGoogleMIM\googleapps-managementagent-master\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 413
Forefront Identity Manager 4.3.2064.0"

**Comment by ryannewington** [comment]
@briuccio, it looks like you may have missed a step in setting up the service account. Did you enable domain wide delegation?

https://stackoverflow.com/questions/42784640/client-is-unauthorized-to-retrieve-access-tokens-using-this-method-gmail-api-c-s

If not, go over the service account setup steps from the wiki again very carefully and make sure you didn't overlook something.

**Comment by briuccio** [comment]
Hi Ryan,
Thank you for your quick answer.
The domain wide delegation is enabled. 
Meanwhile I'm trying to re-create the API client access for the service account.

Thank you

**Comment by ryannewington** [comment]
@briuccio, these Google error messages can be very cryptic, so it's a bit hard for me to tell what was missed. The other thing I can think of is the account you created the service account for needs to be a super admin. Happy to get on a screen sharing session to see if I can help sometime next week if you still get stuck. Same offer goes to you @Expat1905 

Ryan

**Comment by briuccio** [comment]
Hello Ryan,
I'm trying to following your guide from scratch. 
In the first step:
Step 1. Create a new user in your Google Apps instance, and make this user an administrator. This will be the account the FIM service uses to administrator the Google Apps instance.
What kind of permission does the user must have? The user with which I created the service account is NOT super admin.

Thank you.

**Comment by ryannewington** [comment]
@briuccio, I've only been able to get it to work with a super admin account. It may be possible to create a custom role for this, but it would be a process of elimination to determine the correct permissions.

Permissions-wise, the MA needs access to
* Read the list of domains in the tenant
* Read/write users
* Read/write contacts
* Read/write groups
* Read/write group settings
* Read/write group members
* Read/write user custom schema
* Read/write calendar resources
* Read/write calendar ACLs

**Comment by ryannewington** [comment]
Hi @briuccio @myFIMGithub @Expat1905 ,

I have to apologize, as this was a documentation fault. 

In #26 I modified the MA to require reduced permissions in order to run. However, the wiki guide was not updated correctly at the time. Specifically, the MA was asking for read-only permission to the user schema (https://www.googleapis.com/auth/admin.directory.userschema.readonly) however, the scope was granting read/write (https://www.googleapis.com/auth/admin.directory.userschema). Google requires an exact match, and even though we were granting read as well as write access, it would fail with the message you all were seeing.

So the fix is to use the following scopes when authorizing your service account

```
https://www.googleapis.com/auth/admin.directory.domain.readonly,https://apps-apis.google.com/a/feeds/emailsettings/2.0/,http://www.google.com/m8/feeds/contacts/,https://www.googleapis.com/auth/admin.directory.user,https://www.googleapis.com/auth/admin.directory.group,https://www.googleapis.com/auth/admin.directory.group.member,https://www.googleapis.com/auth/admin.directory.userschema.readonly,https://www.googleapis.com/auth/apps.groups.settings,https://www.googleapis.com/auth/admin.directory.resource.calendar,https://www.googleapis.com/auth/calendar
```

My apologies again for the mix up and any inconvenience caused.

Ryan

**Comment by briuccio** [comment]
Hi @ryannewington,
I did your guide from scratch, re-created service account and used the scopes that you wrote on this thread but still the same issue is given.
"Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"unauthorized_client", Description:"Client is unauthorized to retrieve access tokens using this method.", Uri:""
I'm not sure if it means something but the user which I'm using for creating the service account on the console is not super admin, may this cause the issue?
thank you.

**Comment by briuccio** [comment]
solved.. something in the autherization process failed. Thank you!
