### ISSUE TITLE
Google MA deleting the connectorspace object on import exception

### ISSUE THREAD

**Issue by Manjunath-hk1** [lithnet/googleapps-managementagent#36]
Hi Ryan,

We found as issue with FI which had a successful run, but It deleted the contacts from connectorspace. There was an exception with Full import for contacts when this happened.

DLL Version : 2.0.6954

![image](https://user-images.githubusercontent.com/26698594/51952958-85c8dc00-248e-11e9-9d91-3c5956cfe971.png)
```
Exception : 

****************************************
****************************************
Inner exception details
Type: Google.GData.Client.GDataRequestException

Message: Execution of request failed: https://www.google.com/m8/feeds/contacts/ga-staff-staging.monash.edu/full?start-index=5001&max-results=1000
Source: Google.GData.Client
TargetSite: Void Execute()
StackTrace:
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.Service.Query(Uri queryUri, DateTime ifModifiedSince, String etag, Int64& contentLength)
   at Google.GData.Client.Service.Query(FeedQuery feedQuery)
   at Google.GData.Contacts.ContactsService.Query(ContactsQuery feedQuery)
   at Lithnet.GoogleApps.ContactRequestFactory.<>c__DisplayClass3_1.<GetContacts>b__0()
   at Lithnet.GoogleApps.ApiExtensions.InvokeWithRateLimit[T](Func`1 t, String bucketName, Int32 consumeTokens)
   at Lithnet.GoogleApps.ContactRequestFactory.<GetContacts>d__3.MoveNext()
   at Lithnet.GoogleApps.MA.ApiInterfaceContact.<>c__DisplayClass21_0.<GetObjectImportTask>b__0() in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceContact.cs:line 200
   at System.Threading.Tasks.Task.Execute()
****************************************
****************************************
Inner exception details
Type: System.Net.WebException
Status: ProtocolError

Message: The remote server returned an error: (500) Internal Server Error.
Source: System
TargetSite: System.Net.WebResponse GetResponse()
StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
****************************************
```
Thanks,
Manju

**Comment by ryannewington** [comment]
@Manjunath-hk1 this has been fixed and will be included in the next build
