### ISSUE TITLE
Specified cast is not valid while creating group

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/googleapps-managementagent#5]
Event viewer log

Also during this export nothing was written to ma-operations.log but export did happen and group got created

> ECMA2 MA export run caused an error. 
>  
> Error Name: Specified cast is not valid. 
> Error Detail:    at Lithnet.GoogleApps.MA.SchemaBuilder.<>c.<AddGroupSettings>b__13_2(Object value) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\Schema\SchemaBuilder.cs:line 1307
>    at Lithnet.GoogleApps.MA.AdapterPropertyValue.UpdateField(CSEntryChange csentry, Object obj) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\AttributeAdapters\AdapterPropertyValue.cs:line 80
>    at Lithnet.GoogleApps.MA.ApiInterfaceGroupSettings.ApplyChanges(CSEntryChange csentry, SchemaType type, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroupSettings.cs:line 30
>    at Lithnet.GoogleApps.MA.ApiInterfaceGroup.ApplyChanges(CSEntryChange csentry, SchemaType type, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroup.cs:line 117
>    at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeAdd(CSEntryChange csentry, CSEntryChange deltaCSEntry, MASchemaType maType, SchemaType type) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 102
>    at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeObject(CSEntryChange csentry, SchemaType type) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 59
>    at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChange(CSEntryChange csentry, SchemaType type) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 16
>    at Lithnet.GoogleApps.MA.ManagementAgent.<>c__DisplayClass33_0.<PutExportEntries>b__0(CSEntryChange csentry) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 136

**Comment by khandelwalpiyush** [comment]
Latest build [v1.1.6089](https://github.com/lithnet/googleapps-managementagent/releases/tag/v1.1.6089) fixes it
