### ISSUE TITLE
Error exporting students to classroom/course

### ISSUE THREAD

**Issue by magnus1111111** [lithnet/googleapps-managementagent#58]
Getting the following error when exporting multiple students to a classroom
"Number of tokens required is greated than the capacity of the bucket
Parameter name: tokensRequired"

It works when exporting 3 students but when I try with 9 students I get the error. Don't know the exact number of students when the error occurs.

The details of the error are
 at Lithnet.GoogleApps.TokenBucket.TryConsume(Int64 tokensRequired)
   at Lithnet.GoogleApps.TokenBucket.Consume(Int64 numTokens)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetryOnBackoff(BatchRequest request, String serviceName, Int32 retryAttempts, Int32 consumeTokens)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetryOnBackoff(BatchRequest request, String serviceName, Int32 retryAttempts)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetryOnBackoff(BatchRequest request, String serviceName)
   at Lithnet.GoogleApps.CourseStudentRequestFactory.ProcessBatches[T](String id, Boolean ignoreExistingStudent, Boolean ignoreMissingStudent, IList`1 requests, PoolItem`1 poolService, Func`2 onResponse)
   at Lithnet.GoogleApps.CourseStudentRequestFactory.AddStudents(String courseId, IList`1 students, Boolean throwOnExistingStudent)
   at Lithnet.GoogleApps.MA.ApiInterfaceCourseStudents.ApplyChanges(CSEntryChange csentry, SchemaType type, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceCourseStudents.cs:line 78
   at Lithnet.GoogleApps.MA.ApiInterfaceCourse.ApplyChanges(CSEntryChange csentry, SchemaType type, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceCourse.cs:line 169
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeUpdate(CSEntryChange csentry, CSEntryChange deltaCSEntry, MASchemaType maType, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 143
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeObject(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 64
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChange(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 16
   at Lithnet.GoogleApps.MA.ManagementAgent.<>c__DisplayClass32_0.<PutExportEntries>b__0(CSEntryChange csentry) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ManagementAgent.cs:line 134

**Comment by ryannewington** [comment]
@leoerlandsson Looks like the batch size is set to 100 for the class room service, but the rate limiter config for the classroom service only allows 5 requests per second. So any batch requests greater than 5 are failing.

https://developers.google.com/classroom/limits

It looks like we might be able to push 25/sec according to the above limits, but this would still fall sort of the batch size. Thoughts?

**Comment by leoerlandsson** [comment]
Hi @ryannewington @magnus1111111,

There's definitely a problem here. 

I'll have a look at it and get back to you asap. I think it should be a fairly simple fix to just adjust the limits and batch sizes.

Br
Leo

**Comment by leoerlandsson** [comment]
This seems related to https://github.com/lithnet/googleapps-client/issues/2

But that one should be fixed. Investigating further.

**Comment by magnus1111111** [comment]
Any news on this issue?

Br
Magnus

**Comment by leoerlandsson** [comment]
@magnus1111111  I think there's a solution in the above mentioned commits, but I need to test it and then we need to do a new Release. Will keep you updated.

**Comment by ryannewington** [comment]
@leoerlandsson to get @magnus1111111 up and running, should I try a build that just drops the page size down to <5 as a workaround? Until we have more time to look into this further? 

Sorry to have to rely on you for this, but I dont have a classroom enabled tenant to accurately test this stuff out

**Comment by leoerlandsson** [comment]
@ryannewington No worries. Sorry I haven't responded, it's been really busy here.

I have two older commits in my forks that should fix this. I'll try to create Pull requests for them.

There are some other stuff in the commits, but we'll exclude those as they haven't been tested properly.

**Comment by leoerlandsson** [comment]
I've created two pull requests, please see above @ryannewington @magnus1111111 

I'm in Training today and Wednesday, but please don't hestitate to comment should there be any questions. I'll try responding asap.

**Comment by ryannewington** [comment]
[Lithnet.GoogleApps.MA.Setup.zip](https://github.com/lithnet/googleapps-managementagent/files/5302569/Lithnet.GoogleApps.MA.Setup.zip)
@magnus1111111 give this build a go and let us know how you go

**Comment by magnus1111111** [comment]
I'll give at go and let you know

**Comment by magnus1111111** [comment]
I've done a quick test with one classroom that should have 18 students and MIM exported all students in one export without errors. So it seems to work. Thanks.

**Comment by leoerlandsson** [comment]
I guess this needs to be incorporated in master and released officially aswell.

**Comment by ryannewington** [comment]
Thanks for the reminder! published!

**Comment by leoerlandsson** [comment]
Thanks Ryan
