### ISSUE TITLE
Transient object

### ISSUE THREAD

**Issue by briuccio** [lithnet/googleapps-managementagent#66]
Hello,
I set up a provisioning flow where for each group from google MIM will provision a contact in an Active Directory.
I found out that many object from Lithnet Agent are marked as "transient" but they are also projected in metaverse and, for provisioning logic, they are also created as a contact in active directory.
I'm sure that objects marked as transient are not available anymore on Google, so the question is why they are not removed from the connector space after a full import of the agent?

Thank for your help.

Regards.

**Comment by ryannewington** [comment]
Hi @briuccio 

sorry for the delay in responding. In the `Global Parameters` section of the MA, have you assigned a `Contact DN prefix`? If not, try setting this to `contact:`

This can happen if contacts have the same email address of objects in the directory. Setting a prefix helps ensure they always have a unique DN

**Comment by briuccio** [comment]
Hi @ryannewington ,

thank you for your answer.
this is the setting that I have right now:

![image](https://user-images.githubusercontent.com/42810833/121645858-f6d42180-ca94-11eb-9788-9980e4599ce6.png)

After some research I found out that, someone in my organization, delete and recreate a group when is needed to remove all members from that group. The mim see a different anchor (google id) but same DN (mail) and set that group as Transient in the connector space. For some reason it seems that the object deleted from google is keeped in the connector space of lithnet.

Still I need to set a prefix to contact DN?

Thank  you

**Comment by ryannewington** [comment]
That makes sense. FIM will report an object as transient on a DN/anchor change like you reported.

A full import should remove any object from the connector space that no longer exists in the feed from Google.

However, be aware that FIM may not remove obsolete objects from the connector space if there were errors or warnings on import. Youll need to ensure that you perform a full import that completes with a successful (no warnings or errors) result. Once this happens, FIM releases any deleted objects from the connector space

**Comment by briuccio** [comment]
You are perfectly right. We can't get a completed full import without error because there are some groups on google that begins with "#"
![image](https://user-images.githubusercontent.com/42810833/121651050-7e705f00-ca9a-11eb-8ad2-0569e756f152.png)

Is there any way, as per your experience, to filter those groups in the import phase? Even if we have a rule extension on the connector filter? 

Thanks

**Comment by ryannewington** [comment]
Is that a bug with the connector that we need to fix? Can you share the section of the import log that contains one of these  errors?

**Comment by briuccio** [comment]
I can't find anything in the ma-operations.log. I paste here the error that i got in the gui

at Google.Apis.Services.BaseClientService.<DeserializeError>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, Func`2 shouldRetry, Int32 retryAttempts, Int32 consumeTokens)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, RetryEvents policy, Int32 retryAttempts, Int32 consumeTokens)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, RetryEvents policy)

**Comment by ryannewington** [comment]
Thanks, that is the error information I'm looking for but it seems to be truncated. Can you see if there is a complete version of this stack trace in the windows event log?

**Comment by briuccio** [comment]
I found this

ECMA2 MA import run caused an error. 
 
Error Name: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/groups/v1/groups/</code> was not found on this server.  <ins>That’s all we know.</ins>
 
Error Detail:    at Google.Apis.Services.BaseClientService.<DeserializeError>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, Func`2 shouldRetry, Int32 retryAttempts, Int32 consumeTokens)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, RetryEvents policy, Int32 retryAttempts, Int32 consumeTokens)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, RetryEvents policy)
   at Lithnet.GoogleApps.GroupSettingsRequestFactory.Get(String mail)
   at Lithnet.GoogleApps.GroupRequestFactory.<>c__DisplayClass14_0.<ConsumeGroupSettingsQueue>b__0(GoogleGroup group)

**Comment by ryannewington** [comment]
@briuccio  I'm struggling to reproduce this one. 

I can create a group in google that has a name starting with #, and I dont run into any issues.

However, it won't let me create one with an email address starting with #

Are you able to give me some guidance on how to reproduce this situation?

**Comment by briuccio** [comment]
Hello Ryan,
sorry for late reply.
I resolved the issue by filtering objects with mail that contains # and by run a full import without errors. The transient object were released.

The issue occurs when a group with email address starting with # is read from an import by lithnet and the error that I wrote before occurs. The fun fact is that those groups where created with lithnet as well :)
