### ISSUE TITLE
Error importing group with a slash in the email address

### ISSUE THREAD

**Issue by kcrosby** [lithnet/googleapps-managementagent#81]
We are running into an issue when importing groups that have a slash in the email address. It appears from the Event Log entry that it is interpreting the slash in the email address as a slash in the URL, and therefore the object is not found.

The (redacted) email address of the group is "something_a/b-test-reports@domain.com" and the URL it tries to get is:

/groups/v1/groups/something_a/b-test-reports@domain.com?alt=json

I think the email address needs to be URL encoded so that the URL is:

/groups/v1/groups/something_a%2Fb-test-reports%40domain.com?alt=json

We are running into with groups, but I would imagine it would be an issue with any object type.

ECMA2 MA import run caused an error. 
Error Name: <!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>Error 404 (Not Found)!!1</title>
<style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//
[www.google.com/images/errors/robot.png)](https://www.google.com/images/errors/robot.png))
100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//
[www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png)](https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png))
no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//
[www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)](https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png))
no-repeat 0% 0%/100% 100%;-moz-border-image:url(//
[www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)](https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png))
0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//
[www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)](https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png))
no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
</style>
<a href=//
[www.google.com/><span](https://www.google.com/%3E%3Cspan)
id=logo aria-label=Google></span></a>
<p><b>404.</b> <ins>That’s an error.</ins>
<p>The requested URL <code>/groups/v1/groups/something_a/b-test-reports@domain.com?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>
Error Detail:    at Google.Apis.Services.BaseClientService.<DeserializeError>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, Func`2 shouldRetry, Int32 retryAttempts, Int32 consumeTokens)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, RetryEvents policy, Int32 retryAttempts, Int32 consumeTokens)
   at Lithnet.GoogleApps.ApiExtensions.ExecuteWithRetry[T](ClientServiceRequest`1 request, RetryEvents policy)
   at Lithnet.GoogleApps.GroupSettingsRequestFactory.Get(String mail)
   at Lithnet.GoogleApps.GroupRequestFactory.<>c__DisplayClass14_0.<ConsumeGroupSettingsQueue>b__0(GoogleGroup group)

**Comment by ryannewington** [comment]
Hi @kcrosby  

I created a group `something_a/b-test-reports@domain.com` in my domain and I'm not seeing this issue. I can get/update/delete it using the email address, and the slash is encoded correctly. What version of the MA are you running?

Ryan
