### ISSUE TITLE
Adding manager who is an existing member fails

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/googleapps-managementagent#9]
1) Created a group with only a member
2) Tried to add a manager who is the same member

Error

*******************************************************************************
21/09/2016 9:21:21 AM: Opening export connection
-------------------------------------------------------------------------------
21/09/2016 9:21:30 AM: Starting export Update for testgroup-l@d2-monash-edu.ga-staff-dev.monash.edu
21/09/2016 9:21:30 AM: Performing FULL update operation for testgroup-l@d2-monash-edu.ga-staff-dev.monash.edu
****************************************
An exception has occurred in PutCSEntryChange
Type: Google.GoogleApiException
Message: Google.Apis.Requests.RequestError
Member already exists. [409]
Errors [
	Message[Member already exists.] Location[ - ] Reason[duplicate] Domain[global]
]
Failed member add: mgr-piyushk@d2.ga-staff-dev.monash.edu
Group: testgroup-l@d2-monash-edu.ga-staff-dev.monash.edu
Source: Lithnet.GoogleApps
TargetSite: Void AddMembers(System.String, System.Collections.Generic.IList`1[Google.Apis.Admin.Directory.directory_v1.Data.Member], Boolean)
StackTrace:
   at Lithnet.GoogleApps.GroupMemberRequestFactory.AddMembers(String id, IList`1 members, Boolean throwOnExistingMember)
   at Lithnet.GoogleApps.MA.ApiInterfaceGroupMembership.ApplyChanges(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroupMembership.cs:line 78
   at Lithnet.GoogleApps.MA.ApiInterfaceGroup.ApplyChanges(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config, Object& target, Boolean patch) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ApiInterfaces\ApiInterfaceGroup.cs:line 120
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeUpdate(CSEntryChange csentry, CSEntryChange deltaCSEntry, MASchemaType maType, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 144
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChangeObject(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 65
   at Lithnet.GoogleApps.MA.ExportProcessor.PutCSEntryChange(CSEntryChange csentry, SchemaType type, IManagementAgentParameters config) in D:\github\lithnet\googleapps-managementagent\src\Lithnet.GoogleApps.MA\ExportProcessor.cs:line 16
****************************************
-------------------------------------------------------------------------------
21/09/2016 9:21:32 AM: Closing export connection: Normal
21/09/2016 9:21:32 AM: Writing 0 delta entries to file
*******************************************************************************

**Comment by khandelwalpiyush** [comment]
This is on v1.1.6100
The reverse scenario whereby a group with one manager - added one member who is the manager as well fails.. 

But if there are multiple members and then add one of them as manager it works..

**Comment by ryannewington** [comment]
Try this build

[Lithnet.GoogleApps.MA.Setup.zip](https://github.com/lithnet/googleapps-managementagent/files/486254/Lithnet.GoogleApps.MA.Setup.zip)

**Comment by khandelwalpiyush** [comment]
Test - Added one member then him as manager. It didn't change the role

**Comment by ryannewington** [comment]
[Lithnet.GoogleApps.MA.Setup.msi.zip](https://github.com/lithnet/googleapps-managementagent/files/486425/Lithnet.GoogleApps.MA.Setup.msi.zip)
Take 2

**Comment by khandelwalpiyush** [comment]
same result.. does not work

**Comment by ryannewington** [comment]
[Lithnet.GoogleApps.MA.Setup.zip](https://github.com/lithnet/googleapps-managementagent/files/535367/Lithnet.GoogleApps.MA.Setup.zip)
Take 3

**Comment by khandelwalpiyush** [comment]
Delete scenario of a manager does  not work.. it remove it as a member as well from google

**Comment by ryannewington** [comment]
What about original scenario "Adding manager who is an existing member fails "?

**Comment by khandelwalpiyush** [comment]
Works..

**Comment by ryannewington** [comment]
Fixed in v1.1.6135
